### ISSUE TITLE
Crashes when application is backgrounded

### ISSUE THREAD

**Issue by rweichler** [luisespinoza/LEColorPicker#5] opened 2013-08-29 04:41 UTC
When you  try run the color picker while the app is backgrounded, a gpus_ReturnNotPermittedKillClient gets thrown, which is when OpenGL actions are triggered while an app is backgrounded.

**Comment by luisespinoza** [comment] 2013-08-29 13:18
Thanks Again!, this is a **very** important issue. Just one question (to know how to reproduce the crash): **are you periodically requesting color to LEColorPicker right?.**

**Comment by rweichler** [comment] 2013-08-29 13:23
Yeah, once every 3-4 minutes, like when I'm playing a song in the background and it switches to another song (and thus fetches the colors for its artwork), BOOM it crashes. At first I had no idea what it was but I eventually figured out it was from LEColorPicker. I'd just raise an exception or something if the user tries to pick colors and explain to them that it can't be called in the background or something

**Comment by luisespinoza** [comment] 2013-08-29 13:44
OK, thank you for the feedback. I will fix it ASAP

**Comment by luisespinoza** [comment] 2013-08-30 13:16
@rweichler , I have another question. Which background mode is using your app?, which app delegate method is calling the LEColorPicker code?

**Comment by rweichler** [comment] 2013-08-30 13:49
I'm not using any App Delegate method to call the LEColorPicker code. I
call it when a song is playing that needs to get colors from its album
artwork.

**Comment by alextrob** [comment] 2013-08-30 14:03
I'm getting the same issue, only when running on device.

In my case, the background color of a UITableViewCell is set (asynchronously) with LEColorPicker. So if I do a big scroll on the table view and press the home button to put the app in the background while it's still scrolling, it pretty much immediately crashes in the background on `[LEColorPicker setupContext]` (line 304).

**Comment by luisespinoza** [comment] 2013-08-30 14:27
Ok @rweichler

**Comment by luisespinoza** [comment] 2013-08-30 14:33
@alextrob thanks for the feedback. That will be easy for testing. The crash happens because apps should not use the GPU in background, as [Apple docs](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ImplementingaMultitasking-awareOpenGLESApplication/ImplementingaMultitasking-awareOpenGLESApplication.html#//apple_ref/doc/uid/TP40008793-CH5-SW1) explain. Since LEColorPicker uses GPU, is crashing your app. Sorry for the inconvenience. I hope to fix this before Sunday.

**Comment by rweichler** [comment] 2013-08-31 18:39
Are you going to save all of the blocks in an array and call them when the Application re-enters the background or just throw an exception?

**Comment by luisespinoza** [comment] 2013-09-02 01:09
Hi!, I've updated LEColorPicker trying to fix this issue. Please, try the code in  branch "hotfix-issue5". I'll be waiting for your feedback before merge this changes into master. 

Good Night

**Comment by alextrob** [comment] 2013-09-02 12:49
I was still getting crashes at first, but realized it was because the notification observers weren't being removed. Once I added the following to `LEColorPicker.m` I stopped getting crashes.

``` objc
- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationWillResignActiveNotification object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationDidEnterBackgroundNotification object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationWillEnterForegroundNotification object:nil];
}
```

**Comment by luisespinoza** [comment] 2013-09-02 13:18
Sorry, I forgot. I will add those lines tonight. Thanks!

**Comment by luisespinoza** [comment] 2013-09-03 01:50
@alextrob @rweichler correction done. Waiting for feedback. Try branch **hotfix-issue5**.

**Comment by alextrob** [comment] 2013-09-03 07:59
Looking good for me so far. Nice work :)

**Comment by luisespinoza** [comment] 2013-09-05 04:00
@alextrob @rweichler Changes merged. Thanks again for your input!

**Closed as completed by luisespinoza** 2013-09-05 04:00 UTC
Labels: bug
